[package]
name = "ZenithTA"
version = "1.0.0"
edition = "2021"

[lib]
name = "ZenithTA"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.25.0", features = ["extension-module"] }
numpy = "0.25.0"
num-traits = "0.2"

[build-dependencies]
pyo3-build-config = "0.25.0"

[env]
PYTHON_SYS_EXECUTABLE = { value = "/opt/homebrew/bin/python3", force = true }
PYO3_PYTHON = { value = "/opt/homebrew/bin/python3", force = true }

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false
lto = true
