[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "ZenithTA"
version = "0.1.0"
description = "Technical Analysis library written in Rust"
requires-python = ">=3.8"
license = { file = "LICENSE" }
dependencies = [
    "numpy>=1.26.0",
    "pandas>=2.2.0"
]

[tool.uv.workspace]
members = ["speed_tests"]

[tool.maturin]
python-source = "."
module-name = "ZenithTA"
